import { create } from 'zustand';
import { persist } from 'zustand/middleware';

// Traductions complètes FR/EN
const translations = {
  fr: {
    // Navbar
    navbar: {
      home: 'Accueil',
      services: 'Services',
      trading: 'Trading',
      vacation: 'Vacances Junior',
      consultation: 'Consultation',
      login: 'Connexion',
      register: 'Rejoindre Gratuitement',
      mySpace: 'Mon Espace',
      logout: 'Déconnexion',
    },
    // Sidebar
    sidebar: {
      dashboard: 'Tableau de bord',
      prospects: 'Prospects',
      banners: 'Bannières',
      statistics: 'Statistiques',
      settings: 'Paramètres',
      emailGuide: 'Guide Email',
      logout: 'Déconnexion',
      trainers: 'Formateurs',
      videos: 'Vidéos Annonces',
      // Client sidebar
      services: 'Services',
      tradingInfo: 'Le Trading',
      academy: 'Inscription Académie',
      broker: 'Lien Broker',
      contact: 'Contact',
      consultationForm: 'Fiche Consultation',
      vacationProgram: 'Programme Vacances',
      announcements: 'Annonces',
      // Trainer sidebar
      profile: 'Mon Profil',
      registration: 'Ma Fiche d\'inscription',
      strategies: 'Mes Stratégies',
      myVideos: 'Mes Vidéos',
      pages: 'Pages',
      trainerApplication: 'Candidature Formateur',
    },
    // Dashboard
    dashboard: {
      title: 'Tableau de bord Administrateur',
      welcome: 'Bienvenue',
      totalProspects: 'Prospects Totaux',
      conversionRate: 'Taux de Conversion',
      newProspects: 'Nouveaux',
      contacted: 'Contactés',
      converted: 'Convertis',
      rejected: 'Rejetés',
      thisMonth: 'ce mois',
      toProcess: 'À traiter',
      inProgress: 'En suivi',
      clientTitle: 'Tableau de bord Élève',
      trainerTitle: 'Tableau de bord Formateur',
    },
    // Prospects
    prospects: {
      title: 'Gestion des Prospects',
      roundRobin: 'Round-Robin',
      all: 'Tous',
      new: 'Nouveau',
      contactedStatus: 'Contacté',
      convertedStatus: 'Converti',
      rejectedStatus: 'Rejeté',
      loading: 'Chargement...',
      noProspects: 'Aucun prospect trouvé. Les nouveaux prospects seront automatiquement assignés.',
      assignedTo: 'Assigné à',
      process: 'Traiter',
      markContacted: 'Marquer Contacté',
      cancel: 'Annuler',
      addComment: 'Ajouter un commentaire de suivi...',
    },
    // Banners
    banners: {
      title: 'Gestion Bannière Accueil',
      slider: 'Slider',
      addImage: 'Ajouter une image',
      uploading: 'Upload en cours...',
      noImages: 'Aucune image personnalisée (Images par défaut utilisées)',
      deleteConfirm: 'Supprimer cette image ?',
    },
    // Statistics
    statistics: {
      title: 'Bilan Statistique',
      globalProgress: 'Progression globale',
      conversion: 'de conversion',
    },
    // Email Guide
    emailGuide: {
      title: 'Guide Configuration Email Pro',
      subtitle: 'Comment configurer votre email de domaine',
      step1: 'Achetez votre nom de domaine (GoDaddy, Namecheap).',
      step2: 'Prenez un hébergement email (Google Workspace, Zoho Mail).',
      step3: 'Configurez les enregistrements MX dans votre DNS.',
      step4: 'Configurez SPF et DKIM pour éviter les spams.',
    },
    // Home page
    home: {
      newProgram: 'Nouveau : Programme Vacances 2026',
      heroTitle: 'Maîtrisez l\'Art du',
      heroTitleHighlight: 'Trading Forex',
      heroDescription: 'Rejoignez l\'élite des traders. Formation complète, coaching en direct et stratégies gagnantes pour atteindre votre indépendance financière.',
      startFree: 'Commencer Gratuitement',
      discoverTrading: 'Découvrir le Trading',
      students: 'Étudiants',
      satisfaction: 'Satisfaction',
      support: 'Support',
      whyChooseUs: 'Pourquoi nous choisir ?',
      whyChooseUsDesc: 'Une approche pédagogique unique basée sur la pratique.',
      videoTraining: 'Formation Vidéo HD',
      videoTrainingDesc: 'Accédez à une bibliothèque complète de cours, du niveau débutant à expert, disponible 24/7.',
      activeCommunity: 'Communauté Active',
      activeCommunityDesc: 'Échangez avec d\'autres traders, partagez vos analyses et progressez ensemble dans nos groupes privés.',
      secureStrategies: 'Stratégies Sécurisées',
      secureStrategiesDesc: 'Apprenez le Money Management strict pour protéger votre capital et durer sur les marchés.',
      vacationProgram: 'Programme Vacances',
      tradingJunior: 'Trading Junior',
      vacationDesc: 'Initiez vos enfants de 15 à 18 ans au monde de la finance pendant les vacances. Formation ludique et professionnelle avec certificat.',
      julySessions: 'Sessions Juillet & Août',
      maxGroups: 'Groupes de 10 max',
      certificate: 'Certificat délivré',
      discoverProgram: 'Découvrir le Programme',
      startingFrom: 'À partir de',
      twoWeeks: '2 semaines de formation',
      reserveSpot: 'Réserver une Place',
      evaluateLevel: 'Évaluez votre niveau gratuitement',
      evaluateLevelDesc: 'Remplissez notre fiche de consultation et recevez un programme de formation personnalisé adapté à votre profil et vos objectifs.',
      freeConsultation: 'Consultation Gratuite',
      trustedPartner: 'Partenaire de Confiance',
      trustedPartnerDesc: 'Pour réussir en trading, le choix du courtier est crucial. Nous avons sélectionné pour vous le meilleur partenaire : spreads serrés, exécution rapide et retraits sécurisés.',
      openRealAccount: 'Ouvrir un Compte Réel',
      instantDeposits: 'Dépôts Instantanés',
      support247: 'Support 24/7',
      regulated: 'Régulé & Sécurisé',
      stayConnected: 'Restez connecté',
      copyright: '© 2024 LiveFx Academy. Tous droits réservés. Le trading comporte des risques.',
      marketAnalysis: 'Analyse de Marché',
      realTimeUpdate: 'Mise à jour en temps réel',
    },
    // Register
    register: {
      title: 'Inscription',
      subtitle: 'Rejoignez LiveFx Academy',
      fullName: 'Nom complet',
      email: 'Email',
      phone: 'Téléphone (WhatsApp)',
      password: 'Mot de passe',
      iAm: 'Je suis :',
      student: 'Élève / Étudiant',
      studentDesc: 'Je veux apprendre le trading et rejoindre l\'académie',
      trainer: 'Formateur',
      trainerDesc: 'Je suis un trader expérimenté et je veux former des élèves',
      submit: 'S\'inscrire',
      alreadyAccount: 'Déjà un compte ?',
      loginHere: 'Connectez-vous ici',
      nameTooShort: 'Nom trop court',
      invalidEmail: 'Email invalide',
      invalidPhone: 'Numéro invalide',
      passwordTooShort: 'Mot de passe trop court (min 6)',
      successMessage: 'Compte créé avec succès ! Connectez-vous.',
      errorMessage: 'Erreur lors de l\'inscription',
      userExists: 'Un compte existe déjà avec cet email',
    },
    // Login
    login: {
      title: 'Connexion',
      email: 'Email',
      password: 'Mot de passe',
      submit: 'Se connecter',
      noAccount: 'Pas de compte ?',
      registerHere: 'Inscrivez-vous ici',
      errorMessage: 'Erreur de connexion',
      successMessage: 'Connexion réussie !',
      invalidCredentials: 'Email ou mot de passe incorrect',
      forgotPassword: 'Mot de passe oublié ?',
    },
    // Mot de passe oublié
    forgot: {
      title: 'Réinitialiser le mot de passe',
      subtitle: 'Saisissez votre email et votre téléphone pour définir un nouveau mot de passe.',
      email: 'Email',
      phone: 'Téléphone (enregistré sur le compte)',
      newPassword: 'Nouveau mot de passe',
      submit: 'Changer le mot de passe',
      close: 'Fermer',
      successMessage: 'Mot de passe changé avec succès ! Connectez-vous.',
      errorMessage: 'Échec de la réinitialisation',
    },
    // Trading Info
    trading: {
      title: 'Qu\'est-ce que le Trading ?',
      subtitle: 'Comprendre les marchés financiers',
      intro: 'Le trading est l\'activité d\'acheter et vendre des actifs financiers sur les marchés, dans le but de réaliser des profits.',
      forexTitle: 'Le Forex',
      forexDesc: 'Le marché des changes (Forex) est le plus grand marché financier au monde avec plus de 6 000 milliards de dollars échangés chaque jour.',
      advantagesTitle: 'Avantages du Trading',
      advantage1: 'Flexibilité horaire - Tradez 24h/24, 5j/7',
      advantage2: 'Accessibilité - Commencez avec un petit capital',
      advantage3: 'Effet de levier - Multipliez vos gains potentiels',
      advantage4: 'Liquidité - Achetez et vendez instantanément',
      risksTitle: 'Comprendre les Risques',
      risksDesc: 'Le trading comporte des risques. Il est essentiel de se former correctement et de ne jamais investir plus que ce que vous pouvez vous permettre de perdre.',
      startLearning: 'Commencer à Apprendre',
    },
    // Client Dashboard
    client: {
      welcome: 'Bienvenue dans votre espace',
      progression: 'Progression',
      latestAnnouncements: 'Dernières Annonces Vidéo',
      by: 'Par',
      servicesTitle: 'Nos Services',
      servicesDesc: 'Découvrez tous les services de LiveFx Academy',
      tradingInfoTitle: 'Le Trading',
      tradingInfoDesc: 'Apprenez les bases et concepts avancés du trading',
      academyTitle: 'Inscription Académie',
      academyDesc: 'Rejoignez notre programme de formation complet',
      brokerTitle: 'Lien Broker Partenaire',
      brokerDesc: 'Ouvrez un compte chez notre courtier partenaire',
      contactTitle: 'Nous Contacter',
      whatsapp: 'WhatsApp',
      telegram: 'Canal Telegram',
      facebook: 'Page Facebook',
      consultationTitle: 'Fiche de Consultation',
      consultationDesc: 'Partagez votre progression pour un suivi personnalisé',
      fillForm: 'Remplir la fiche',
      vacationTitle: 'Programme Vacances Junior',
      vacationDesc: 'Formation trading pour les 15-18 ans',
      noAnnouncements: 'Aucune annonce vidéo pour le moment',
    },
    // Trainer
    trainer: {
      welcome: 'Bienvenue Formateur',
      profileTitle: 'Mon Profil',
      registrationTitle: 'Ma Fiche d\'inscription',
      strategiesTitle: 'Mes Stratégies',
      addStrategy: 'Ajouter une stratégie',
      editStrategy: 'Modifier',
      deleteStrategy: 'Supprimer',
      strategyName: 'Nom de la stratégie',
      strategyDesc: 'Description',
      marketType: 'Type de marché',
      timeframe: 'Timeframe',
      riskReward: 'Ratio R/R',
      winRate: 'Taux de réussite',
      entryCriteria: 'Critères d\'entrée',
      exitCriteria: 'Critères de sortie',
      riskManagement: 'Gestion du risque',
    },
    // Common
    common: {
      refresh: 'Actualiser',
      delete: 'Supprimer',
      save: 'Enregistrer',
      error: 'Erreur',
      success: 'Succès',
      cancel: 'Annuler',
      edit: 'Modifier',
      add: 'Ajouter',
      submit: 'Envoyer',
      loading: 'Chargement...',
      viewDetails: 'Voir détails',
      networkError: 'Impossible de joindre le serveur. Vérifiez votre connexion internet.',
      timeoutError: 'Le serveur met trop de temps à répondre. Réessayez dans un instant.',
      unknownError: 'Une erreur inattendue est survenue.',
    },
  },
  en: {
    // Navbar
    navbar: {
      home: 'Home',
      services: 'Services',
      trading: 'Trading',
      vacation: 'Junior Vacation',
      consultation: 'Consultation',
      login: 'Login',
      register: 'Join Free',
      mySpace: 'My Space',
      logout: 'Logout',
    },
    // Sidebar
    sidebar: {
      dashboard: 'Dashboard',
      prospects: 'Prospects',
      banners: 'Banners',
      statistics: 'Statistics',
      settings: 'Settings',
      emailGuide: 'Email Guide',
      logout: 'Logout',
      trainers: 'Trainers',
      videos: 'Video Announcements',
      // Client sidebar
      services: 'Services',
      tradingInfo: 'Trading',
      academy: 'Academy Registration',
      broker: 'Broker Link',
      contact: 'Contact',
      consultationForm: 'Consultation Form',
      vacationProgram: 'Vacation Program',
      announcements: 'Announcements',
      // Trainer sidebar
      profile: 'My Profile',
      registration: 'My Registration',
      strategies: 'My Strategies',
      myVideos: 'My Videos',
      pages: 'Pages',
      trainerApplication: 'Trainer Application',
    },
    // Dashboard
    dashboard: {
      title: 'Admin Dashboard',
      welcome: 'Welcome',
      totalProspects: 'Total Prospects',
      conversionRate: 'Conversion Rate',
      newProspects: 'New',
      contacted: 'Contacted',
      converted: 'Converted',
      rejected: 'Rejected',
      thisMonth: 'this month',
      toProcess: 'To process',
      inProgress: 'In progress',
      clientTitle: 'Student Dashboard',
      trainerTitle: 'Trainer Dashboard',
    },
    // Prospects
    prospects: {
      title: 'Prospects Management',
      roundRobin: 'Round-Robin',
      all: 'All',
      new: 'New',
      contactedStatus: 'Contacted',
      convertedStatus: 'Converted',
      rejectedStatus: 'Rejected',
      loading: 'Loading...',
      noProspects: 'No prospects found. New prospects will be automatically assigned.',
      assignedTo: 'Assigned to',
      process: 'Process',
      markContacted: 'Mark Contacted',
      cancel: 'Cancel',
      addComment: 'Add a follow-up comment...',
    },
    // Banners
    banners: {
      title: 'Home Banner Management',
      slider: 'Slider',
      addImage: 'Add an image',
      uploading: 'Uploading...',
      noImages: 'No custom images (Default images used)',
      deleteConfirm: 'Delete this image?',
    },
    // Statistics
    statistics: {
      title: 'Statistics Overview',
      globalProgress: 'Global Progress',
      conversion: 'conversion',
    },
    // Email Guide
    emailGuide: {
      title: 'Professional Email Setup Guide',
      subtitle: 'How to configure your domain email',
      step1: 'Buy your domain name (GoDaddy, Namecheap).',
      step2: 'Get email hosting (Google Workspace, Zoho Mail).',
      step3: 'Configure MX records in your DNS.',
      step4: 'Set up SPF and DKIM to avoid spam.',
    },
    // Home page
    home: {
      newProgram: 'New: Vacation Program 2026',
      heroTitle: 'Master the Art of',
      heroTitleHighlight: 'Forex Trading',
      heroDescription: 'Join the trading elite. Complete training, live coaching and winning strategies to achieve your financial independence.',
      startFree: 'Start Free',
      discoverTrading: 'Discover Trading',
      students: 'Students',
      satisfaction: 'Satisfaction',
      support: 'Support',
      whyChooseUs: 'Why choose us?',
      whyChooseUsDesc: 'A unique educational approach based on practice.',
      videoTraining: 'HD Video Training',
      videoTrainingDesc: 'Access a complete library of courses, from beginner to expert level, available 24/7.',
      activeCommunity: 'Active Community',
      activeCommunityDesc: 'Exchange with other traders, share your analyses and progress together in our private groups.',
      secureStrategies: 'Secure Strategies',
      secureStrategiesDesc: 'Learn strict Money Management to protect your capital and last in the markets.',
      vacationProgram: 'Vacation Program',
      tradingJunior: 'Junior Trading',
      vacationDesc: 'Introduce your children aged 15-18 to the world of finance during the holidays. Fun and professional training with certificate.',
      julySessions: 'July & August Sessions',
      maxGroups: 'Groups of 10 max',
      certificate: 'Certificate issued',
      discoverProgram: 'Discover the Program',
      startingFrom: 'Starting from',
      twoWeeks: '2 weeks of training',
      reserveSpot: 'Reserve a Spot',
      evaluateLevel: 'Evaluate your level for free',
      evaluateLevelDesc: 'Fill out our consultation form and receive a personalized training program tailored to your profile and goals.',
      freeConsultation: 'Free Consultation',
      trustedPartner: 'Trusted Partner',
      trustedPartnerDesc: 'To succeed in trading, choosing the right broker is crucial. We have selected the best partner for you: tight spreads, fast execution and secure withdrawals.',
      openRealAccount: 'Open a Real Account',
      instantDeposits: 'Instant Deposits',
      support247: '24/7 Support',
      regulated: 'Regulated & Secure',
      stayConnected: 'Stay connected',
      copyright: '© 2024 LiveFx Academy. All rights reserved. Trading involves risks.',
      marketAnalysis: 'Market Analysis',
      realTimeUpdate: 'Real-time update',
    },
    // Register
    register: {
      title: 'Registration',
      subtitle: 'Join LiveFx Academy',
      fullName: 'Full name',
      email: 'Email',
      phone: 'Phone (WhatsApp)',
      password: 'Password',
      iAm: 'I am:',
      student: 'Student',
      studentDesc: 'I want to learn trading and join the academy',
      trainer: 'Trainer',
      trainerDesc: 'I am an experienced trader and I want to train students',
      submit: 'Register',
      alreadyAccount: 'Already have an account?',
      loginHere: 'Login here',
      nameTooShort: 'Name too short',
      invalidEmail: 'Invalid email',
      invalidPhone: 'Invalid phone number',
      passwordTooShort: 'Password too short (min 6)',
      successMessage: 'Account created successfully! Please login.',
      errorMessage: 'Registration error',
      userExists: 'An account already exists with this email',
    },
    // Login
    login: {
      title: 'Login',
      email: 'Email',
      password: 'Password',
      submit: 'Login',
      noAccount: 'No account?',
      registerHere: 'Register here',
      errorMessage: 'Login error',
      successMessage: 'Login successful!',
      invalidCredentials: 'Incorrect email or password',
      forgotPassword: 'Forgot password?',
    },
    // Forgot password
    forgot: {
      title: 'Reset password',
      subtitle: 'Enter your email and phone number to set a new password.',
      email: 'Email',
      phone: 'Phone (registered on the account)',
      newPassword: 'New password',
      submit: 'Change password',
      close: 'Close',
      successMessage: 'Password changed successfully! Please login.',
      errorMessage: 'Reset failed',
    },
    // Trading Info
    trading: {
      title: 'What is Trading?',
      subtitle: 'Understanding Financial Markets',
      intro: 'Trading is the activity of buying and selling financial assets in the markets, with the aim of making profits.',
      forexTitle: 'Forex',
      forexDesc: 'The foreign exchange market (Forex) is the largest financial market in the world with over $6 trillion traded every day.',
      advantagesTitle: 'Trading Advantages',
      advantage1: 'Time flexibility - Trade 24/5',
      advantage2: 'Accessibility - Start with small capital',
      advantage3: 'Leverage - Multiply your potential gains',
      advantage4: 'Liquidity - Buy and sell instantly',
      risksTitle: 'Understanding Risks',
      risksDesc: 'Trading involves risks. It is essential to train properly and never invest more than you can afford to lose.',
      startLearning: 'Start Learning',
    },
    // Client Dashboard
    client: {
      welcome: 'Welcome to your space',
      progression: 'Progression',
      latestAnnouncements: 'Latest Video Announcements',
      by: 'By',
      servicesTitle: 'Our Services',
      servicesDesc: 'Discover all LiveFx Academy services',
      tradingInfoTitle: 'Trading',
      tradingInfoDesc: 'Learn the basics and advanced concepts of trading',
      academyTitle: 'Academy Registration',
      academyDesc: 'Join our complete training program',
      brokerTitle: 'Partner Broker Link',
      brokerDesc: 'Open an account with our partner broker',
      contactTitle: 'Contact Us',
      whatsapp: 'WhatsApp',
      telegram: 'Telegram Channel',
      facebook: 'Facebook Page',
      consultationTitle: 'Consultation Form',
      consultationDesc: 'Share your progress for personalized follow-up',
      fillForm: 'Fill out the form',
      vacationTitle: 'Junior Vacation Program',
      vacationDesc: 'Trading training for ages 15-18',
      noAnnouncements: 'No video announcements yet',
    },
    // Trainer
    trainer: {
      welcome: 'Welcome Trainer',
      profileTitle: 'My Profile',
      registrationTitle: 'My Registration',
      strategiesTitle: 'My Strategies',
      addStrategy: 'Add a strategy',
      editStrategy: 'Edit',
      deleteStrategy: 'Delete',
      strategyName: 'Strategy name',
      strategyDesc: 'Description',
      marketType: 'Market type',
      timeframe: 'Timeframe',
      riskReward: 'R/R Ratio',
      winRate: 'Win rate',
      entryCriteria: 'Entry criteria',
      exitCriteria: 'Exit criteria',
      riskManagement: 'Risk management',
    },
    // Common
    common: {
      refresh: 'Refresh',
      delete: 'Delete',
      save: 'Save',
      error: 'Error',
      success: 'Success',
      cancel: 'Cancel',
      edit: 'Edit',
      add: 'Add',
      submit: 'Submit',
      loading: 'Loading...',
      viewDetails: 'View details',
      networkError: 'Cannot reach the server. Please check your internet connection.',
      timeoutError: 'The server is taking too long to respond. Please try again shortly.',
      unknownError: 'An unexpected error occurred.',
    },
  },
};

export const useLanguageStore = create(
  persist(
    (set, get) => ({
      language: 'fr',
      setLanguage: (lang) => set({ language: lang }),
      toggleLanguage: () => set({ language: get().language === 'fr' ? 'en' : 'fr' }),
      t: (key) => {
        const lang = get().language;
        const keys = key.split('.');
        let value = translations[lang];
        for (const k of keys) {
          value = value?.[k];
        }
        return value || key;
      },
    }),
    {
      name: 'livefx-language',
    }
  )
);